package com.mycompany.proyectosistemafacturacion;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        setUndecorated(true);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 16, 16));
            }
        });
        initComponents();
        LoginFrame frame = new LoginFrame();
        lblUserName.setText(frame.user);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rSPanelGradiente1 = new rojeru_san.rspanel.RSPanelGradiente();
        rSLabelSombra1 = new rojeru_san.rslabel.RSLabelSombra();
        materialButton2 = new necesario.MaterialButton();
        jbuttonProveedor = new necesario.MaterialButton();
        materialButton4 = new necesario.MaterialButton();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelSombra2 = new rojeru_san.rslabel.RSLabelSombra();
        lblUserName = new rojeru_san.rslabel.RSLabelSombra();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(103, 71, 206));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(150, 68, 205));

        rSLabelSombra1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelSombra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSLabelSombra1.setText("Menú Principal");
        rSLabelSombra1.setColorDeSombra(new java.awt.Color(204, 0, 255));
        rSLabelSombra1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSLabelSombra1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(rSLabelSombra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel2.add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 396, -1));

        materialButton2.setBackground(new java.awt.Color(103, 71, 206));
        materialButton2.setForeground(new java.awt.Color(255, 255, 255));
        materialButton2.setText("Clientes");
        materialButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 172, -1, -1));

        jbuttonProveedor.setBackground(new java.awt.Color(103, 71, 206));
        jbuttonProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonProveedor.setText("Proveedor");
        jbuttonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jbuttonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 121, -1, -1));

        materialButton4.setBackground(new java.awt.Color(103, 71, 206));
        materialButton4.setForeground(new java.awt.Color(255, 255, 255));
        materialButton4.setText("Productos");
        materialButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 223, -1, -1));

        rSLabelIcon1.setForeground(new java.awt.Color(103, 71, 206));
        jPanel2.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        rSLabelSombra2.setForeground(new java.awt.Color(0, 204, 0));
        rSLabelSombra2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rSLabelSombra2.setText("Online");
        rSLabelSombra2.setColorDeSombra(new java.awt.Color(255, 255, 255));
        rSLabelSombra2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jPanel2.add(rSLabelSombra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 60, 19));

        lblUserName.setForeground(new java.awt.Color(103, 71, 206));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName.setText("Online");
        lblUserName.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 177, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton4ActionPerformed
        Producto producto = new Producto();
        producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materialButton4ActionPerformed

    private void jbuttonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonProveedorActionPerformed
        Proveedor proveedor = new Proveedor();
        proveedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbuttonProveedorActionPerformed

    private void materialButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton2ActionPerformed
        Clientes clientes = new Clientes();
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materialButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private necesario.MaterialButton jbuttonProveedor;
    private rojeru_san.rslabel.RSLabelSombra lblUserName;
    private necesario.MaterialButton materialButton2;
    private necesario.MaterialButton materialButton4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private rojeru_san.rslabel.RSLabelSombra rSLabelSombra1;
    private rojeru_san.rslabel.RSLabelSombra rSLabelSombra2;
    private rojeru_san.rspanel.RSPanelGradiente rSPanelGradiente1;
    // End of variables declaration//GEN-END:variables
}
